In [1]:
import pandas as pd
dframe = pd.read_csv("data/sample/US_1_dating/segment_united states_1_dating_asian.csv")

dframe.head()

,Unnamed: 0,Unnamed: 0.1,1,2,3,4,5,6,7,8,...,left_eye_status.no_glass_eye_open,left_eye_status.normal_glass_eye_close,left_eye_status.dark_glasses,right_eye_status.normal_glass_eye_open,right_eye_status.no_glass_eye_close,right_eye_status.occlusion,right_eye_status.no_glass_eye_open,right_eye_status.normal_glass_eye_close,right_eye_status.dark_glasses,ethnicity.value
0,0,1769,-0.615642,1.946491,-0.616038,-0.369693,3.822441,-0.503009,-0.395748,-0.533025,...,100.0,0.0,0.0,0.0,0.4,0.0,99.6,0.0,0.0,asian
1,1,2514,-0.611850,-0.387335,-0.636436,-0.541266,-0.423150,-0.705734,0.548963,-0.539531,...,99.9,0.0,0.0,0.0,0.0,0.9,98.8,0.0,0.3,asian
2,2,3231,-0.615844,-0.691398,0.443463,-0.678009,2.623850,-0.610400,-0.527724,-0.546390,...,100.0,0.0,0.0,0.1,0.0,0.0,99.9,0.0,0.0,asian
3,3,3409,3.628956,0.230938,-0.624318,3.716962,-0.468125,-0.706332,-0.527686,-0.547682,...,100.0,0.0,0.0,0.6,0.0,0.0,99.4,0.0,0.0,asian
4,4,4121,-0.616153,0.010111,-0.419755,-0.628964,-0.574333,-0.507126,1.005461,-0.545319,...,100.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,asian

In [10]:
def make_dummies(dataframe = dframe):
    temp_df = dataframe.drop("pol",axis =1)
    cat_columns = temp_df .select_dtypes("object").columns
    dummy_df = pd.get_dummies(temp_df[list(cat_columns)])

    return pd.concat([dataframe.drop(cat_columns,axis =1 ), dummy_df], axis = 1)

,Unnamed: 0,Unnamed: 0.1,1,2,3,4,5,6,7,8,...,left_eye_status.dark_glasses,right_eye_status.normal_glass_eye_open,right_eye_status.no_glass_eye_close,right_eye_status.occlusion,right_eye_status.no_glass_eye_open,right_eye_status.normal_glass_eye_close,right_eye_status.dark_glasses,country_united states,database_dating,ethnicity.value_asian
0,0,1769,-0.615642,1.946491,-0.616038,-0.369693,3.822441,-0.503009,-0.395748,-0.533025,...,0.0,0.0,0.4,0.0,99.6,0.0,0.0,1,1,1
1,1,2514,-0.611850,-0.387335,-0.636436,-0.541266,-0.423150,-0.705734,0.548963,-0.539531,...,0.0,0.0,0.0,0.9,98.8,0.0,0.3,1,1,1
2,2,3231,-0.615844,-0.691398,0.443463,-0.678009,2.623850,-0.610400,-0.527724,-0.546390,...,0.0,0.1,0.0,0.0,99.9,0.0,0.0,1,1,1
3,3,3409,3.628956,0.230938,-0.624318,3.716962,-0.468125,-0.706332,-0.527686,-0.547682,...,0.0,0.6,0.0,0.0,99.4,0.0,0.0,1,1,1
4,4,4121,-0.616153,0.010111,-0.419755,-0.628964,-0.574333,-0.507126,1.005461,-0.545319,...,0.0,0.0,0.0,0.0,100.0,0.0,0.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,49318,-0.593745,-0.017506,-0.636648,-0.640871,-0.553330,2.119187,-0.521240,-0.035091,...,0.0,0.2,0.0,0.1,99.7,0.0,0.0,1,1,1
996,996,49339,-0.550093,1.547542,-0.635994,1.096647,-0.443414,-0.130495,3.178733,-0.544991,...,0.0,0.2,0.0,0.0,99.8,0.0,0.0,1,1,1
997,997,49354,-0.606170,-0.714945,-0.524223,-0.715984,-0.205687,-0.702091,-0.527252,3.854402,...,0.0,0.7,0.0,0.0,99.2,0.0,0.0,1,1,1
998,998,49392,0.445182,2.069954,-0.636708,-0.296112,1.792980,1.129792,1.412088,-0.525227,...,0.0,0.0,0.0,0.1,99.9,0.0,0.0,1,1,1
999,999,49422,-0.594821,3.470431,-0.297315,-0.179468,0.176469,1.312564,-0.046634,-0.479259,...,0.0,99.6,0.0,0.0,0.4,0.0,0.0,1,1,1

In [ ]:
cat_cols = extracted_df.select_dtypes(include=['object']).columns
num_df =